# Site wide configuration

title:            Barbara Tozier Photographer
locale:           en_US
url:


# Jekyll configuration

permalink:   /:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  # parse_block_html: true

# Site owner
owner:
  name: Barbara Tozier
  avatar: website/tozier-avatar.jpg
  bio: "I'm a photographer who gets up close and personal with *things*."
  email: info@barbaratozier.com
  twitter: logista
  google:
    plus: logista
    analytics:
    verify:
    ad-client:
    ad-slot:
  github: logista
  tumblr: logista


include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "notes to myself.txt"]

links:
  - title: Writings
    url: /writings/

defaults:
  -
    scope:
      path: ""
    values:
      share: false
